// Generated by CIRCT firtool-1.62.0
module Arty100Top(
  input        CLK100MHZ,
               ck_rst,
  input  [3:0] sw,
               btn,
  output [3:0] led,
  output       led0_b,
               led0_g,
               led0_r,
               led1_b,
               led1_g,
               led1_r,
               led2_b,
               led2_g,
               led2_r,
               led3_b,
               led3_g,
               led3_r,
               uart_rxd_out,
  input        uart_txd_in,
               eth_col,
               eth_crs,
  output       eth_ref_clk,
               eth_rstn,
  input        eth_rx_clk,
               eth_rx_dv,
  input  [3:0] eth_rxd,
  input        eth_rxerr,
  output       eth_tx_clk,
               eth_tx_en,
  output [3:0] eth_txd
);

  wire _eth_io_led4;
  wire _eth_io_led5;
  wire _eth_io_led6;
  wire _eth_io_led7;
  wire _sync_reset_inst_out;
  wire _clk_bufg_inst_O;
  wire _mmcm_CLKOUT0;
  wire _mmcm_CLKOUT1;
  wire _mmcm_CLKFBOUT;
  wire _mmcm_LOCKED;
  wire _clk_ibufg_inst_O;
  IBUFG clk_ibufg_inst (
    .I (CLK100MHZ),
    .O (_clk_ibufg_inst_O)
  );
  MMCME2_BASE #(
    .BANDWIDTH("OPTIMIZED"),
    .CLKFBOUT_MULT_F(10),
    .CLKFBOUT_PHASE(0),
    .CLKIN1_PERIOD(1.000000e+01),
    .CLKOUT0_DIVIDE_F(8),
    .CLKOUT0_DUTY_CYCLE(5.000000e-01),
    .CLKOUT0_PHASE(0),
    .CLKOUT1_DIVIDE(40),
    .CLKOUT1_DUTY_CYCLE(5.000000e-01),
    .CLKOUT1_PHASE(0),
    .CLKOUT2_DIVIDE(1),
    .CLKOUT2_DUTY_CYCLE(5.000000e-01),
    .CLKOUT2_PHASE(0),
    .CLKOUT3_DIVIDE(1),
    .CLKOUT3_DUTY_CYCLE(5.000000e-01),
    .CLKOUT3_PHASE(0),
    .CLKOUT4_CASCADE("FALSE"),
    .CLKOUT4_DIVIDE(1),
    .CLKOUT4_DUTY_CYCLE(5.000000e-01),
    .CLKOUT4_PHASE(0),
    .CLKOUT5_DIVIDE(1),
    .CLKOUT5_DUTY_CYCLE(5.000000e-01),
    .CLKOUT5_PHASE(0),
    .CLKOUT6_DIVIDE(1),
    .CLKOUT6_DUTY_CYCLE(5.000000e-01),
    .CLKOUT6_PHASE(0),
    .DIVCLK_DIVIDE(1),
    .REF_JITTER1(1.000000e-02),
    .STARTUP_WAIT("FALSE")
  ) mmcm (
    .CLKIN1    (_clk_ibufg_inst_O),
    .CLKFBIN   (_mmcm_CLKFBOUT),
    .RST       (~ck_rst),
    .PWRDWN    (1'h0),
    .CLKOUT0   (_mmcm_CLKOUT0),
    .CLKOUT0B  (/* unused */),
    .CLKOUT1   (_mmcm_CLKOUT1),
    .CLKOUT1B  (/* unused */),
    .CLKOUT2   (/* unused */),
    .CLKOUT2B  (/* unused */),
    .CLKOUT3   (/* unused */),
    .CLKOUT3B  (/* unused */),
    .CLKOUT4   (/* unused */),
    .CLKOUT5   (/* unused */),
    .CLKOUT6   (/* unused */),
    .CLKFBOUT  (_mmcm_CLKFBOUT),
    .CLKFBOUTB (/* unused */),
    .LOCKED    (_mmcm_LOCKED)
  );
  BUFG clk_25mhz_bufg_inst (
    .I (_mmcm_CLKOUT1),
    .O (eth_ref_clk)
  );
  BUFG clk_bufg_inst (
    .I (_mmcm_CLKOUT0),
    .O (_clk_bufg_inst_O)
  );
  SyncReset #(
    .N(4)
  ) sync_reset_inst (
    .clk (_mmcm_CLKOUT0),
    .rst (~_mmcm_LOCKED),
    .out (_sync_reset_inst_out)
  );
  Ethernet eth (
    .clock          (_clk_bufg_inst_O),
    .reset          (_sync_reset_inst_out),
    .io_led0_r      (led0_r),
    .io_led0_g      (led0_g),
    .io_led0_b      (led0_b),
    .io_led1_r      (led1_r),
    .io_led1_g      (led1_g),
    .io_led1_b      (led1_b),
    .io_led2_r      (led2_r),
    .io_led2_g      (led2_g),
    .io_led2_b      (led2_b),
    .io_led3_r      (led3_r),
    .io_led3_g      (led3_g),
    .io_led3_b      (led3_b),
    .io_led4        (_eth_io_led4),
    .io_led5        (_eth_io_led5),
    .io_led6        (_eth_io_led6),
    .io_led7        (_eth_io_led7),
    .io_phy_col     (eth_col),
    .io_phy_crs     (eth_crs),
    .io_phy_reset_n (eth_rstn),
    .io_phy_rx_clk  (eth_rx_clk),
    .io_phy_rx_dv   (eth_rx_dv),
    .io_phy_rxd     (eth_rxd),
    .io_phy_rx_er   (eth_rxerr),
    .io_phy_tx_clk  (eth_tx_clk),
    .io_phy_tx_en   (eth_tx_en),
    .io_phy_txd     (eth_txd)
  );
  assign led = {_eth_io_led7, _eth_io_led6, _eth_io_led5, _eth_io_led4};
  assign uart_rxd_out = uart_txd_in;
endmodule

