// Generated by CIRCT firtool-1.62.0
// external module IBUFG

// external module MMCME2_BASE

// external module BUFG

// external module SyncReset

// external module EthernetWrap

// external module eth_axis_tx

// external module eth_axis_rx

// external module axis_fifo

// external module eth_mac_mii_fifo

